"""Public contracts for the trusted built-in Skill System."""

from .commerce import (
    ALLOWED_TOOL_CAPABILITIES,
    COMMERCE_ANALYTICS_MANIFEST,
    CommerceAnalyticsSkill,
    logical_plan_from_eval_case,
)
from .models import (
    AnalysisType,
    CalculationOperation,
    CrossTabSpec,
    DerivedCalculation,
    FilterOperator,
    GrainAlignment,
    LogicalFilter,
    LogicalOrdering,
    LogicalQueryPlan,
    PlanContext,
    RankingSpec,
    ResultShape,
    SeriesAxis,
    SkillInput,
    SkillManifest,
    SortDirection,
    TimeGrain,
    TimeRange,
    WindowSpec,
)
from .registry import BUILTIN_SKILL_REGISTRY, SkillRegistry
from .validation import (
    CommercePlanValidator,
    PlanValidationCode,
    PlanValidationError,
    PlanValidationIssue,
    PlanValidationResult,
    expected_result_shape,
    relationship_ids_for_entities,
)

__all__ = [
    "ALLOWED_TOOL_CAPABILITIES",
    "BUILTIN_SKILL_REGISTRY",
    "COMMERCE_ANALYTICS_MANIFEST",
    "AnalysisType",
    "CalculationOperation",
    "CrossTabSpec",
    "CommerceAnalyticsSkill",
    "CommercePlanValidator",
    "DerivedCalculation",
    "FilterOperator",
    "GrainAlignment",
    "LogicalFilter",
    "LogicalOrdering",
    "LogicalQueryPlan",
    "PlanContext",
    "PlanValidationCode",
    "PlanValidationError",
    "PlanValidationIssue",
    "PlanValidationResult",
    "ResultShape",
    "RankingSpec",
    "SeriesAxis",
    "SkillInput",
    "SkillManifest",
    "SkillRegistry",
    "SortDirection",
    "TimeGrain",
    "TimeRange",
    "WindowSpec",
    "expected_result_shape",
    "logical_plan_from_eval_case",
    "relationship_ids_for_entities",
]
