"""The runtime skeleton and built-in Commerce graph fragment."""

from __future__ import annotations

from data_agent.runtime.models import AgentMode

from .compiler import ExecutionGraphCompiler
from .models import (
    ArtifactKind,
    BudgetLimits,
    EdgeCondition,
    EdgeSpec,
    ErrorBudget,
    ErrorCode,
    ErrorRouteSpec,
    GraphFragment,
    NodeKind,
    NodeSpec,
)


def _terminal(code: ErrorCode) -> ErrorRouteSpec:
    return ErrorRouteSpec(code=code, terminal=True)


ACCESS_DENIED_ROUTE = _terminal(ErrorCode.ACCESS_DENIED)


RUNTIME_SKELETON = GraphFragment(
    fragment_id="runtime.skeleton",
    nodes=(
        NodeSpec(
            id="resolve_context",
            kind=NodeKind.PURE,
            outputs=(ArtifactKind.RESOLVED_CONTEXT,),
        ),
        NodeSpec(
            id="finalize",
            kind=NodeKind.TERMINAL,
            inputs=(
                ArtifactKind.STATIC_VALIDATION,
                ArtifactKind.ANSWER,
            ),
            outputs=(ArtifactKind.FINAL,),
        ),
    ),
)


COMMERCE_ANALYTICS_FRAGMENT = GraphFragment(
    fragment_id="commerce.analytics",
    nodes=(
        NodeSpec(
            id="semantic_search",
            kind=NodeKind.TOOL,
            tool_ref="semantic.search",
            inputs=(ArtifactKind.RESOLVED_CONTEXT,),
            outputs=(ArtifactKind.SEMANTIC_MATCHES,),
            on_error=(ACCESS_DENIED_ROUTE,),
        ),
        NodeSpec(
            id="build_logical_plan",
            kind=NodeKind.PLANNER,
            inputs=(
                ArtifactKind.RESOLVED_CONTEXT,
                ArtifactKind.SEMANTIC_MATCHES,
            ),
            outputs=(ArtifactKind.LOGICAL_PLAN,),
        ),
        NodeSpec(
            id="validate_logical_plan",
            kind=NodeKind.VALIDATOR,
            inputs=(ArtifactKind.LOGICAL_PLAN,),
            outputs=(ArtifactKind.PLAN_VALIDATION,),
            on_error=(
                ErrorRouteSpec(
                    code=ErrorCode.LOGICAL_PLAN_INVALID,
                    target="build_logical_plan",
                    retryable=True,
                    max_attempts=2,
                    budget=ErrorBudget.CORRECTION,
                ),
            ),
        ),
        NodeSpec(
            id="inspect_binding",
            kind=NodeKind.TOOL,
            tool_ref="data.inspect",
            inputs=(ArtifactKind.LOGICAL_PLAN,),
            outputs=(ArtifactKind.CATALOG_SNAPSHOT,),
            on_error=(ACCESS_DENIED_ROUTE,),
            requires_credentials=True,
        ),
        NodeSpec(
            id="compile_query",
            kind=NodeKind.TOOL,
            tool_ref="query.compile",
            inputs=(
                ArtifactKind.LOGICAL_PLAN,
                ArtifactKind.PLAN_VALIDATION,
                ArtifactKind.CATALOG_SNAPSHOT,
            ),
            outputs=(
                ArtifactKind.BOUND_QUERY_PLAN,
                ArtifactKind.PREPARED_QUERY,
            ),
            on_error=(
                ErrorRouteSpec(
                    code=ErrorCode.LOGICAL_PLAN_INVALID,
                    target="build_logical_plan",
                    retryable=True,
                    max_attempts=2,
                    budget=ErrorBudget.CORRECTION,
                ),
                ErrorRouteSpec(
                    code=ErrorCode.BINDING_STALE,
                    target="inspect_binding",
                    retryable=True,
                    max_attempts=1,
                    budget=ErrorBudget.DIAGNOSTIC,
                    allowed_modes=(AgentMode.PREVIEW, AgentMode.EXECUTE),
                ),
                ErrorRouteSpec(
                    code=ErrorCode.SQL_COMPILE_ERROR,
                    target="compile_query",
                    retryable=True,
                    max_attempts=3,
                    budget=ErrorBudget.SQL_COMPILE,
                ),
                ErrorRouteSpec(
                    code=ErrorCode.SQL_POLICY_VIOLATION,
                    target="compile_query",
                    retryable=True,
                    max_attempts=3,
                    budget=ErrorBudget.SQL_COMPILE,
                ),
                ACCESS_DENIED_ROUTE,
            ),
        ),
        NodeSpec(
            id="validate_query",
            kind=NodeKind.VALIDATOR,
            inputs=(ArtifactKind.PREPARED_QUERY,),
            outputs=(ArtifactKind.STATIC_VALIDATION,),
            on_error=(
                ErrorRouteSpec(
                    code=ErrorCode.SQL_POLICY_VIOLATION,
                    target="compile_query",
                    retryable=True,
                    max_attempts=3,
                    budget=ErrorBudget.SQL_COMPILE,
                ),
                ACCESS_DENIED_ROUTE,
            ),
        ),
        NodeSpec(
            id="explain_cost",
            kind=NodeKind.TOOL,
            tool_ref="query.execute",
            inputs=(ArtifactKind.STATIC_VALIDATION,),
            outputs=(ArtifactKind.EXPLAIN_RESULT,),
            on_error=(
                ErrorRouteSpec(
                    code=ErrorCode.COST_EXCEEDED,
                    target="build_logical_plan",
                    retryable=True,
                    max_attempts=2,
                    budget=ErrorBudget.CORRECTION,
                ),
                ACCESS_DENIED_ROUTE,
            ),
            requires_credentials=True,
        ),
        NodeSpec(
            id="execute_preview",
            kind=NodeKind.TOOL,
            tool_ref="query.execute",
            inputs=(ArtifactKind.EXPLAIN_RESULT,),
            outputs=(ArtifactKind.QUERY_PREVIEW,),
            on_error=(
                ErrorRouteSpec(
                    code=ErrorCode.JOIN_EXPLOSION,
                    target="build_logical_plan",
                    retryable=True,
                    max_attempts=2,
                    budget=ErrorBudget.CORRECTION,
                ),
                ACCESS_DENIED_ROUTE,
            ),
            requires_credentials=True,
        ),
        NodeSpec(
            id="validate_preview",
            kind=NodeKind.VALIDATOR,
            inputs=(ArtifactKind.QUERY_PREVIEW,),
            outputs=(ArtifactKind.PREVIEW_VALIDATION,),
            on_error=(
                ErrorRouteSpec(
                    code=ErrorCode.EMPTY_RESULT,
                    target="build_logical_plan",
                    retryable=True,
                    max_attempts=1,
                    budget=ErrorBudget.DIAGNOSTIC,
                ),
                ErrorRouteSpec(
                    code=ErrorCode.JOIN_EXPLOSION,
                    target="build_logical_plan",
                    retryable=True,
                    max_attempts=2,
                    budget=ErrorBudget.CORRECTION,
                ),
            ),
        ),
        NodeSpec(
            id="execute_query",
            kind=NodeKind.TOOL,
            tool_ref="query.execute",
            inputs=(ArtifactKind.PREVIEW_VALIDATION,),
            outputs=(ArtifactKind.QUERY_RESULT,),
            on_error=(
                ErrorRouteSpec(
                    code=ErrorCode.JOIN_EXPLOSION,
                    target="build_logical_plan",
                    retryable=True,
                    max_attempts=2,
                    budget=ErrorBudget.CORRECTION,
                ),
                ACCESS_DENIED_ROUTE,
            ),
            requires_credentials=True,
        ),
        NodeSpec(
            id="profile_result",
            kind=NodeKind.TOOL,
            tool_ref="result.profile",
            inputs=(
                ArtifactKind.PREVIEW_VALIDATION,
                ArtifactKind.QUERY_RESULT,
            ),
            outputs=(ArtifactKind.RESULT_PROFILE,),
            on_error=(ACCESS_DENIED_ROUTE,),
        ),
        NodeSpec(
            id="validate_result",
            kind=NodeKind.VALIDATOR,
            inputs=(ArtifactKind.RESULT_PROFILE,),
            outputs=(ArtifactKind.RESULT_VALIDATION,),
            on_error=(
                ErrorRouteSpec(
                    code=ErrorCode.RESULT_SEMANTIC_MISMATCH,
                    target="build_logical_plan",
                    retryable=True,
                    max_attempts=1,
                    budget=ErrorBudget.CORRECTION,
                ),
            ),
        ),
        NodeSpec(
            id="render_answer",
            kind=NodeKind.TOOL,
            tool_ref="answer.render",
            inputs=(ArtifactKind.RESULT_VALIDATION,),
            outputs=(ArtifactKind.ANSWER,),
            on_error=(ACCESS_DENIED_ROUTE,),
        ),
    ),
    edges=(
        EdgeSpec(
            source="resolve_context",
            target="semantic_search",
            artifact=ArtifactKind.RESOLVED_CONTEXT,
        ),
        EdgeSpec(
            source="semantic_search",
            target="build_logical_plan",
            artifact=ArtifactKind.SEMANTIC_MATCHES,
        ),
        EdgeSpec(
            source="build_logical_plan",
            target="validate_logical_plan",
            artifact=ArtifactKind.LOGICAL_PLAN,
        ),
        EdgeSpec(
            source="validate_logical_plan",
            target="compile_query",
            artifact=ArtifactKind.PLAN_VALIDATION,
        ),
        EdgeSpec(
            source="inspect_binding",
            target="compile_query",
            artifact=ArtifactKind.CATALOG_SNAPSHOT,
        ),
        EdgeSpec(
            source="compile_query",
            target="validate_query",
            artifact=ArtifactKind.PREPARED_QUERY,
        ),
        EdgeSpec(
            source="validate_query",
            target="finalize",
            condition=EdgeCondition.MODE_PLAN,
            artifact=ArtifactKind.STATIC_VALIDATION,
        ),
        EdgeSpec(
            source="validate_query",
            target="explain_cost",
            condition=EdgeCondition.MODE_NOT_PLAN,
            artifact=ArtifactKind.STATIC_VALIDATION,
        ),
        EdgeSpec(
            source="explain_cost",
            target="execute_preview",
            artifact=ArtifactKind.EXPLAIN_RESULT,
        ),
        EdgeSpec(
            source="execute_preview",
            target="validate_preview",
            artifact=ArtifactKind.QUERY_PREVIEW,
        ),
        EdgeSpec(
            source="validate_preview",
            target="profile_result",
            condition=EdgeCondition.MODE_PREVIEW,
            artifact=ArtifactKind.PREVIEW_VALIDATION,
        ),
        EdgeSpec(
            source="validate_preview",
            target="execute_query",
            condition=EdgeCondition.MODE_EXECUTE,
            artifact=ArtifactKind.PREVIEW_VALIDATION,
        ),
        EdgeSpec(
            source="execute_query",
            target="profile_result",
            artifact=ArtifactKind.QUERY_RESULT,
        ),
        EdgeSpec(
            source="profile_result",
            target="validate_result",
            artifact=ArtifactKind.RESULT_PROFILE,
        ),
        EdgeSpec(
            source="validate_result",
            target="render_answer",
            artifact=ArtifactKind.RESULT_VALIDATION,
        ),
        EdgeSpec(
            source="render_answer",
            target="finalize",
            artifact=ArtifactKind.ANSWER,
        ),
    ),
)


COMMERCE_EXECUTION_GRAPH = ExecutionGraphCompiler().compile(
    graph_id="commerce.execution",
    version="1.0.0",
    entry_node="resolve_context",
    terminal_nodes=("finalize",),
    fragments=(RUNTIME_SKELETON, COMMERCE_ANALYTICS_FRAGMENT),
    limits=BudgetLimits(),
)
