"""Export the browser-packaged AgentResponse schema from the backend OpenAPI."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from api.app import create_app
from data_agent.runtime import AgentResponse


OUTPUT_PATH = (
    PROJECT_ROOT
    / "frontend"
    / "src"
    / "generated"
    / "agent-response.schema.ts"
)
FIXTURE_PATH = (
    PROJECT_ROOT
    / "frontend"
    / "src"
    / "generated"
    / "agent-response.fixture.json"
)
ROOT_SCHEMA = "AgentResponse"
_ANNOTATION_KEYS = frozenset({"default", "description", "title"})
_SCALAR_KEYS = frozenset(
    {"$ref", "const", "enum", "format", "maxItems", "maxLength", "minItems", "minLength", "minimum", "pattern", "required", "type"}
)
_NESTED_KEYS = frozenset({"additionalProperties", "anyOf", "items", "prefixItems", "properties", "propertyNames"})


def build_frontend_agent_response_schema(
    specification: dict[str, Any] | None = None,
) -> dict[str, Any]:
    document = create_app().openapi() if specification is None else specification
    source_schemas = document["components"]["schemas"]
    names = _referenced_schema_names(source_schemas, ROOT_SCHEMA)
    schemas = {
        name: _normalize_schema(source_schemas[name])
        for name in sorted(names)
    }
    return {"root": ROOT_SCHEMA, "schemas": schemas}


def export_frontend_agent_response_schema(
    output_path: str | Path = OUTPUT_PATH,
) -> Path:
    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(
            build_frontend_agent_response_schema(),
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
    destination.write_text(
        "// Generated by scripts/export_frontend_agent_response_schema.py.\n"
        f"const schema = {payload} as const;\n\n"
        "export default schema;\n",
        encoding="utf-8",
    )
    return destination


def export_frontend_agent_response_fixture(
    output_path: str | Path = FIXTURE_PATH,
) -> Path:
    response = AgentResponse.model_validate_json(
        FIXTURE_PATH.read_text(encoding="utf-8")
    )
    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(
            response.model_dump(mode="json", by_alias=True),
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return destination


def _referenced_schema_names(
    schemas: dict[str, Any],
    root: str,
) -> set[str]:
    names = {root}
    pending = [root]
    while pending:
        value = schemas[pending.pop()]
        for reference in _iter_references(value):
            name = reference.removeprefix("#/components/schemas/")
            if name not in schemas:
                raise ValueError(f"unknown OpenAPI schema reference: {reference}")
            if name not in names:
                names.add(name)
                pending.append(name)
    return names


def _iter_references(value: object):
    if isinstance(value, dict):
        reference = value.get("$ref")
        if isinstance(reference, str):
            if not reference.startswith("#/components/schemas/"):
                raise ValueError(f"unsupported OpenAPI reference: {reference}")
            yield reference
        for nested in value.values():
            yield from _iter_references(nested)
    elif isinstance(value, list):
        for nested in value:
            yield from _iter_references(nested)


def _normalize_schema(schema: dict[str, Any]) -> dict[str, Any]:
    normalized: dict[str, Any] = {}
    for key, value in schema.items():
        if key in _ANNOTATION_KEYS:
            continue
        if key in _SCALAR_KEYS:
            normalized[key] = value
            continue
        if key == "properties":
            normalized[key] = {
                name: _normalize_schema(nested)
                for name, nested in sorted(value.items())
            }
            continue
        if key in {"anyOf", "oneOf"}:
            normalized["anyOf"] = [_normalize_schema(nested) for nested in value]
            continue
        if key == "discriminator":
            # Backend Pydantic validation enforces the discriminator. The browser
            # validator evaluates the normalized alternatives and their const kind.
            continue
        if key == "prefixItems":
            normalized[key] = [_normalize_schema(nested) for nested in value]
            continue
        if key in {"items", "propertyNames"}:
            normalized[key] = _normalize_schema(value)
            continue
        if key == "additionalProperties":
            normalized[key] = (
                value if isinstance(value, bool) else _normalize_schema(value)
            )
            continue
        raise ValueError(f"unsupported AgentResponse schema keyword: {key}")

    properties = normalized.get("properties")
    if normalized.get("type") == "object" and isinstance(properties, dict):
        if normalized.get("additionalProperties") is False:
            # Public responses are validated after model_dump(), which includes defaults.
            normalized["required"] = sorted(properties)
    return normalized


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    parser.add_argument("--fixture-output", type=Path, default=FIXTURE_PATH)
    arguments = parser.parse_args(argv)
    print(export_frontend_agent_response_schema(arguments.output))
    print(export_frontend_agent_response_fixture(arguments.fixture_output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
